### ISSUE TITLE
python examples failed on win7

### ISSUE THREAD

**Issue by jjqcat** [lijieumn/argus-distribution#5]
G:\WCTS\argus-distribution-master>python examples/box_and_cone.py
conf\box_and_cone.json
Traceback (most recent call last):
  File "G:\WCTS\argus-distribution-master\examples\argus_interface.py", line 29,
 in <module>
    argus.simulate(display = display, demo = example, save_objects = save, perfo
rmance_file = performance_file, objects_path_given = outputpath)
  File "G:\WCTS\argus-distribution-master\examples\argus.py", line 103, in simul
ate
    subprocess.call(args)
  File "E:\Python36\lib\subprocess.py", line 287, in call
    with Popen(*popenargs, **kwargs) as p:
  File "E:\Python36\lib\subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "E:\Python36\lib\subprocess.py", line 1017, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

G:\WCTS\argus-distribution-master>

**Comment by jjqcat** [comment]
O,I have compiled it on windows, thanks
